name: Deploy to EC2

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/nb07-codi-it-team2

            # 1. 원격 저장소 최신화 및 서버 상태 강제 동기화
            git fetch origin
            git fetch origin
            git reset --hard origin/${{ github.ref_name }}

            # 2. 의존성 설치
            npm install

            # 3. Prisma 클라이언트 갱신 및 DB 동기화
            npx prisma generate

            # 4. 빌드 실행
            npm run build

            # 5. PM2 무중단 재시작 
            pm2 reload ecosystem.config.js --env production
